### ISSUE TITLE
example eks cluster.yaml serviceAccountRoleARN may not be needed

### ISSUE THREAD

**Issue by lolwww** [canonical/kubeflow-examples#45]
for this part of eks-cluster-setup/cluster.yaml

```
addons:
- name: aws-ebs-csi-driver
  serviceAccountRoleARN: "arn:aws:iam::aws:policy/service-role/AmazonEBSCSIDriverPolicy"
  wellKnownPolicies:
   ebsCSIController: true
```
   
I am getting this error:
**$ eksctl create cluster -f cluster.yaml**
_Error: invalid configuration for "aws-ebs-csi-driver" addon: at most one of wellKnownPolicies, serviceAccountRoleARN, attachPolicyARNs and attachPolicy can be specified_

https://github.com/eksctl-io/eksctl/blob/main/pkg/apis/eksctl.io/v1alpha5/addon.go#L187

I believe it should be safe to remove serviceAccountRoleARN as wellKnownPolicies field should be sufficient to grant the necessary permissions for the EBS CSI driver.
